version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - setup_remote_docker
      - checkout
      - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run: with-kind-cluster.sh tilt ci
