version: 2.1
jobs:
  build:
    docker:
      - image: docker/tilt:latest

    steps:
      - setup_remote_docker
      - checkout
      - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-4 | bash
      - run: ctlptl create cluster kind --registry=ctlptl-registry && tilt ci
